# name: my-first-github-action
# on: [push]
# jobs:
#   Leaning-basics-of-github-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: hello world
#         run: echo "HELLO WORLD PRINTED ON GITHUB ACTIONS"
#       - name: cloning the current repo
#         uses: actions/checkout@v2 # important 1
#       - name: see the tree view
#         run: tree
#       - name: see the List
#         run: ls
#       - name: setup node js in my project
#         uses: actions/setup-node@v2 # important 2
#       - name: checking node versions
#         run: node -v
#       - name: Installing node_modules
#         run: npm install # important 3
#       - name: Build the project
#         run: npm run build # important 4
